### ISSUE TITLE
Where is Home/offer.html?

### ISSUE THREAD

**Issue by qujixiang** [Soufiane-Majdar/Food_Project#4]
Hello, could you tell me where is "*.html" referred in index.html?

**Comment by nirmal777** [comment]
The .html is missing in the index.html files, it keeps on getting errors. Even if the block is separated into sections there must be HTML files for individual folders.

**Comment by ipungg-junior** [comment]
yes, there is nothing offer.html file, should create html manually by own?

**Comment by Soufiane-Majdar** [comment]
The issue with the missing HTML files has been fixed. Please refer to the latest commit [commit_hash](https://github.com/Soufiane-Majdar/Food_Project/commit/) for more details.
